[tox]
minversion = 4.0
envlist = py3,pep8
skipsdist = False

[testenv]
usedevelop = True
setenv =
    VIRTUAL_ENV={envdir}
    OS_STDOUT_CAPTURE=1
    OS_STDERR_CAPTURE=1
    OS_TEST_TIMEOUT=60
deps =
    -r{toxinidir}/requirements.txt
    -r{toxinidir}/test-requirements.txt
    --constraint https://opendev.org/openstack/requirements/raw/branch/master/upper-constraints.txt
commands = stestr run {posargs}

[testenv:py3]
basepython = python3

[testenv:pep8]
deps =
    flake8>=6.0.0
commands =
    flake8 nova/virt/nova_rxt

[flake8]
show-source = True
max-line-length = 99
exclude = .tox,dist,build,*.egg-info,.venv
ignore = W503,E203

[testenv:venv]
commands = {posargs}
